### ISSUE TITLE
更统一的留白

### ISSUE THREAD

**Issue by Jeswang** [xsxsxszs/VeXplore-Issues#19]
整个应用都非常喜欢。关于界面的一些建议：
- 帖子列表中几个元素之间的留白不够统一，图标右侧留白太少，文字下方留白太多
- 标题文字的颜色太深，可以参考 V2EX 的配色方案

谢谢。

**Comment by Jeswang** [comment]
图标大小以及留白可以参考微信读书或者 V2EX 网页：

![img_7864](https://cloud.githubusercontent.com/assets/553783/15988515/644ac0b0-3086-11e6-9fe7-180ed8ae08a0.PNG)

**Comment by xsxsxszs** [comment]
@Jeswang 谢谢建议，留白会做细微调整，标题是整个cell的重点，颜色较深是为了让人注意力主要集中在标题上。V站的配色方案不是很喜欢。
