### ISSUE TITLE
主题页面增加关闭方式？

### ISSUE THREAD

**Issue by xsxsxszs** [xsxsxszs/VeXplore-Issues#2]
目前主题页面只支持点击左上角关闭，是否有必要增加关闭方式？

**Comment by amorphobia** [comment]
我也是同样的想法，我是iPhone 6 plus，点击左上角关闭需要两只手才能做到，希望加入滑动返回的功能。

**Comment by xsxsxszs** [comment]
@amorphobia 双指下拉返回，还是右滑返回？ 下拉返回的话，打开和关闭方式比较统一，右滑返回似乎又比较符合用户的本能操作。

**Comment by amorphobia** [comment]
个人倾向于右滑，对于大屏幕已经是默认的了，我也是右滑好几次才意识到没有这个功能。而且下拉的默认作用是刷新。或许对于v2的主题来说刷新是无必要的，可以也作为返回？ anyway，我认为右滑是必要的，可以开个投票问问其他用户。

**Comment by miniers** [comment]
双指的手势还是要两个手来操作啊，和点击左上角差不多了，右划不错，或者单指下拉做成两端，第一段刷新 ，第二段关闭主题，类似于Spark中对邮件的左右滑动两段操作，甚至上拉到底部时也能关闭 😉

**Comment by xsxsxszs** [comment]
@miniers 还是右滑吧，帖子下啦没有刷新的，v2的帖子都不能随便编辑，下拉刷新容易误操作，做无用的网络请求，耗电耗流量。

**Comment by xsxsxszs** [comment]
帖子左滑关闭完成。
