### ISSUE TITLE
应用内点击节点右上角红心无效

### ISSUE THREAD

**Issue by doresu** [xsxsxszs/VeXplore-Issues#35]
点击确认红心以后再进去这个节点依然灰色

**Comment by xsxsxszs** [comment]
@doresu 感谢反馈，的确存在这个问题。我是抓取的手机版V站网页，以前是可以的。发现在手机V站上点击收藏节点后也是无反应，电脑端网页和手机端网页请求的API不一样，这个应该是V站最近改了API，但是手机端并网页没有改，貌似是V站的bug，考虑要不要单独为了这个页面去请求电脑端页面。

**Comment by xsxsxszs** [comment]
已向Livid报告这个bug，但迟迟未修复，故将页面替换成网页版解析。
